title: Henrik Berg

include:
  - '_pages'

plugins:
  - jekyll-feed

author:
  name: 'henrikbg'
  displayName: 'Henrik Berg'
  picture: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=500'
  links:
    -
      name: 'GitHub'
      url: 'https://github.com/henrikbg'
      icon: 'fab fa-github'
    -
      name: 'LinkedIn'
      url: 'https://linkedin.com/in/henrikbg'
      icon: 'fab fa-linkedin'
    -
      name: 'Twitter'
      url: 'https://twitter.com/henrikbg_'
      icon: 'fab fa-twitter'
